export const LOADING_GET_INGREDIENTS =
  'LOADING_GET_INGREDIENTS';
export const SUCCESS_GET_INGREDIENTS =
  'SUCCESS_GET_INGREDIENTS';
export const FAILURE_GET_INGREDIENTS =
  'FAILURE_GET_INGREDIENTS';