export const LOADING_GET_RECIPE_INFORMATION =
  'LOADING_GET_RECIPE_INFORMATION';
export const SUCCESS_GET_RECIPE_INFORMATION =
  'SUCCESS_GET_RECIPE_INFORMATION';
export const FAILURE_GET_RECIPE_INFORMATION =
  'FAILURE_GET_RECIPE_INFORMATION';